### ISSUE TITLE
Feature request: Allow search on JQL query

### ISSUE THREAD

**Issue by Eothred** [marc0l92/joplin-plugin-jira-issue#1]
This plugin already worked very smoothly, nice work!

I have one suggestion, to add JQL search as an option (maybe it is already there and just not in the README example).

For example `resolution = Unresolved AND assignee = username ORDER BY updated DESC` would be one of my immediate thoughts.

**Comment by marc0l92** [comment]
Hello Eothred,
you would like to see multiple issues using one tag configured with a query?

Using a tag like like this:
```html
<JiraIssue query="resolution = Unresolved AND assignee = username ORDER BY updated DESC">
```

you would like to see:
```md
<JiraIssue query="resolution = Unresolved AND assignee = username ORDER BY updated DESC">
<JiraIssue key="AAA-1">... details ... </JiraIssue>
<JiraIssue key="AAA-2">... details ... </JiraIssue>
<JiraIssue key="AAA-3">... details ... </JiraIssue>
```

Is it correct?

**Comment by Eothred** [comment]
Hi, yes that would be quite accurately what I was thinking about. Then I am not sure what would happen on a "refresh", should it change the list (add and delete), maybe just add any new issues from query, or maybe it should rather remove/comment out the query so that it is a frozen list after the first "pull" of issues. I don't really know what would be the best solution here (depends also on what is easier/possible to implement I suppose)

**Comment by Eothred** [comment]
Tested your new work, this looks really brilliant. Thanks a lot! :smiley:

**Comment by marc0l92** [comment]
Thanks for your feedback. Let me know if you have some more suggestions.
