### ISSUE TITLE
Feature Requests - Include labels in summary, auto expand Epics

### ISSUE THREAD

**Issue by ddl-mmercer** [marc0l92/joplin-plugin-jira-issue#11]
Just found this plugin while looking for something that would allow me to use joplin to maintain my confluence documentation (I know.. I know, it was a dream... but hey, I still have hope!)

Anyways, love it!  makes it so much easier than having to try and keep track of tons of things jumping all over in jira...

Two things that would be hugely helpful:
1.) Grab all of the subtasks/subitems in an Epic ticket type.  Would be awesome to not have to manually list them all.
2.) Add labels to the summaries -- this would help give a nice birds eye view of things for those that use labels to help categorize things

**Comment by marc0l92** [comment]
Creating something that sync the joplin notes to confluence is in my todo list. You can create a new topic on joplin forum and we can define together the features we could implement to do the sync.

1. I guess you can take the subtask using a jira query. I usually use the query:
```
"epic link"=AAA-123 AND project IN (TEAM1, TEAM2) ORDER BY key
```
but in your query you can add things like `type = Task` if you need only the tasks.


2. I'm not sure to understand what you need. I'm not a Product Owner so I don't know all the features of Jira.

you are talking about those labels:
![image](https://user-images.githubusercontent.com/12623073/139533083-153b8b87-7290-40c5-8d58-2be8eb609369.png)

and you want to see them inside the jira issue
![image](https://user-images.githubusercontent.com/12623073/139533111-985cd5cf-a8d7-462a-82c6-fb69b1fa215f.png)

**Comment by marc0l92** [comment]
No answer from issue creator
