### ISSUE TITLE
Not possible to login with Atlassian account in Jira Cloud

### ISSUE THREAD

**Issue by vidbaz** [marc0l92/joplin-plugin-jira-issue#12]
Hey Guys,
Thanks for the work, I tried the authentication method but it's not working... for example I am trying with the following url https://exampledomain.atlassian.net/jira/ and my Atlassian credentials.
Is it possible to login with Jira Cloud?
I researched here about the basic authentication https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/#basic-auth-for-rest-apis  and also I already review src/jiraClient.ts and src/settings.ts and looks like the url is build OK, even I tried to generate an API Token and logging with it but no luck.

do you have any clue? 

Error : HTTP status 401

**Comment by marc0l92** [comment]
No reply from the issue creator
