### ISSUE TITLE
No snippet after switching from markdown editor to rendered view

### ISSUE THREAD

**Issue by yukpun** [marc0l92/joplin-plugin-jira-issue#15]
When opened split view (markdown and rendered) this plugin works fine, it grabs Jira issue, show status and so on.
Just after switching to only rendered view, I see this `- Getting issue details... STATUS`
If I switch back to split view, I see Jira snippet. So it works only when markdown editor is open

**Application info**
```
Joplin for Desktop

Copyright © 2016-2022 Laurent Cozic
Joplin 2.7.15 (prod, darwin)

Client ID: 4c24d20fd0574f748b87d47c255c5b72
Sync Version: 3
Profile Version: 41
Keychain Supported: Yes

Revision: 8352e23
```

**OS Version**
`MacOs Monterey 12.3.1`

Tried this with no other plugin installed.

**Comment by marc0l92** [comment]
While I was working on this plugin Joplin did not support any plugin javascript running inside the the "render view"/"rich text mode".

I don't know if in the last updates this has been modified. Are you aware of any other plugin that are able to generate dynamic content in the "render view"?

**Comment by marc0l92** [comment]
Apparently it is still the case.
https://joplinapp.org/rich_text_editor/

![image](https://user-images.githubusercontent.com/12623073/170792682-e6812add-55e7-4fe6-80e6-570d54cf20f5.png)

Actually this was one of the main reason I moved from Joplin to Obsidian. I wanted to get rid of the double column view but keeping all the plugins features.
