### ISSUE TITLE
Can't connect to jira cloud

### ISSUE THREAD

**Issue by EnriqueRS** [marc0l92/joplin-plugin-jira-issue#16]
HI!
I can't use the plugin because my company uses jira cloud. The url is of the following type: namecompany.atlassian.net/jira

Is there any way to use the plugin?

Thanks!

**Comment by kristanner2015** [comment]
You'll need an API token.  You should be able to generate one in your JIRA/Atlassian profile.  I have it working on a <company>.atlassian.net url scheme, but I had to put my corporate email in the "username" field and the API token value in the password field.  I'm using v. 2.3.0 of the plugin.

**Comment by EnriqueRS** [comment]
![image](https://user-images.githubusercontent.com/4162603/169785995-ab30254c-bd4e-4540-b116-2b4d4e4710b6.png)
![image](https://user-images.githubusercontent.com/4162603/169786225-f7223282-7bf0-4dd1-b552-1352cea2690e.png)
This is my configuration, in password field is the JIRA/Atlassian token

**Comment by EnriqueRS** [comment]
Ok, I have solved the problem by deleting 'jira' from the url, leaving it like this:
https://companyname.atlassian.net/

Thanks!
