### ISSUE TITLE
auto-refresh

### ISSUE THREAD

**Issue by aranajuan** [marc0l92/joplin-plugin-jira-issue#4]
Hi! do you think periodic auto-refresh could be posible? Something like https://discourse.joplinapp.org/t/note-overview/13962
see: https://github.com/JackGruber/joplin-plugin-note-overview

- Auto refresh (configurable interval)
- Update all notes with calls to this plugin (not only update current note)
- Remove pop-up (it wont help with auto-update)

tx!

**Comment by marc0l92** [comment]
I'm working on redesigning the plugin in order to provide auto-refresh

**Comment by marc0l92** [comment]
Please download the new major release to get this feature
