### ISSUE TITLE
Password config lost after restart

### ISSUE THREAD

**Issue by aranajuan** [marc0l92/joplin-plugin-jira-issue#5]
After restart Joplin and execute plugin it returns 401 and passwords is deleted from config. I added the same password again and it worked.

**To reproduce**
Joplin for Desktop
Joplin 1.8.1 (prod, darwin)

1_ add issue
2_ refresh Jira status
3_ close and open Joplin
4_ refresh issue status
5_ it shows  "Error: 401" and password is erased

**Comment by SilvM** [comment]
getting the same thing, except I add the password, Apply and try to refresh, the plugin seems to be dead. the context menu to add template doesn't work anymore and I don't see the "Error:401" again until I restart joplin

**Comment by marc0l92** [comment]
The password was not stored due to a Joplin settings API bug. With the new API version the issue is solved.
