### ISSUE TITLE
After changing options and refreshing issues are doubled

### ISSUE THREAD

**Issue by KolyaKorruptis** [marc0l92/joplin-plugin-jira-issue#6]
I changed the options to include **Render: assignee** and hit Refresh issues. Afterwards every issue was inserted a second time in the mark down. First without the  assignee and then again with the assignee.

**Comment by marc0l92** [comment]
Thanks for reporting this issue. Can you give me an example to reproduce the issue?

**Comment by KolyaKorruptis** [comment]
No, the doubling of issues happened too often and your response comes way too late. I stopped using the plugin because of this problem.

**Comment by marc0l92** [comment]
Did you replaced this plugin something else?

**Comment by KolyaKorruptis** [comment]
Well, I switched to Edge browser, which copy & pastes URLs with the title of the website as link text, into Joplin's rich text editor. In my job I create a lot of Jira issue links in Joplin and this helps a lot. While it can't tell me the status of an issue of course, it's a lot faster than fiddling with issue templates.

**Comment by marc0l92** [comment]
Thanks for your usage feedbacks. I'm deprecating the template I was using before in order to implement something more user friendly.
![image](https://user-images.githubusercontent.com/12623073/134497104-627ea4e2-60c6-4f79-8e79-1339977b92bc.png)
In this markdown fence block you will be able to paste the user story link and then see the status in the rendered version.

I will close this issue when I release this new version

**Comment by KolyaKorruptis** [comment]
Will there be a button in the rich editor to mark text as jira issue? This would be preferable.
Or will I have to create a code block, then specify the language as "jira-issue" and then paste the ticket number?

**Comment by marc0l92** [comment]
I don't know how the rich editor works from the plugin development point of view. I will take a look at it.

Do you know any existing plugin that allows some interactions in the rich editor?
In this way I can take a look at their implementation

**Comment by KolyaKorruptis** [comment]
I seem to remember using a few plugins that had buttons in rich editor, but I don't know anymore which did. Sorry.
Maybe I'll find the time to look them up later.

**Comment by marc0l92** [comment]
I will take a look at it as well, but from what I know:
![image](https://user-images.githubusercontent.com/12623073/134651095-d7ae0f72-c0c9-4ccf-bf23-ec9b8f490dbe.png)

**Comment by marc0l92** [comment]
I published a new major version where I redesign the full plugin. I hope that now this issue is fixed
