### ISSUE TITLE
Plugin stops working after refreshing issues on macOS

### ISSUE THREAD

**Issue by DK-Stern** [marc0l92/joplin-plugin-jira-issue#7]
**Problem**
After calling alert() function, the plugin crashes on mac devices.

**Behaviour**
Every time, after refreshing issues, the plugin stops working and i don't get an alert message on mac. I need to restart Joplin to use the plugin again.
It seems that the alert function doesn't work generally on mac, i don't know why.

**Workaorund**
After i saw, that on windows device everything works fine and i get an alert with message "JiraIssue: Refresh completed", i tried to remove following line:

https://github.com/marc0l92/joplin-plugin-jira-issue/blob/47b47765c5d0f02445641bd7ff494f2d969846e5/src/index.ts#L141

After removing this function call, everything works properly fine on mac.

**Tested on Mac**
MacBook Pro (15 inch, 2019)
macOS Big Sur, version 11.0.1
Joplin 1.7.11 (prod, darwin)
Revision: f560563 (master)

**Possible Solution**
Maybe we could use the ['joplin.views.dialogs' command from plugin api](https://joplinapp.org/api/references/plugin_api/classes/joplinviewsdialogs.html) instead of alert function to display the messages on all devices properly. We would need to replace all alert function calls with this command.

**Comment by marc0l92** [comment]
Thanks for the pull request.
I merged your changes and deliver them in v1.7.0 of this plugin
