### ISSUE TITLE
Can't show and access setting with last Joplin verison

### ISSUE THREAD

**Issue by AizeLeOuf** [marc0l92/joplin-plugin-jira-issue#9]
Hi,

First of all, many thanks for this plugin very useful.

I'm trying to use it on the new release of Joplin, and there is no way to access plugin setting from the configuration. Is there a workarround for this issue ?

Regards,

**Comment by marc0l92** [comment]
The compatibility with the new api of Joplin has been fixed in the pull request #10 and it will be release in the plugin version 1.7.0
